name: Test

on: [push, pull_request, workflow_dispatch]

env:
  GITHUB_OWNER: 'moodlehq'
  REPOSITORY: 'asero'

jobs:
  Check-and-Test:
    name: Checks and tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: '3.12'
          - python: '3.13'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: "**/pyproject.toml"
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install .[dev]
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
      - name: Run pre-commit
        run: |
          pre-commit run --all
      - name: Coverage
        run: |
          coverage run
          coverage report
